# Generated by Django 4.2 on 2023-04-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('OPEN', 'Ждет отправки'), ('CLOSED', 'Отправлено'), ('PROCESSED', 'В процессе отправки')], default='CREATED', max_length=20, verbose_name='Статус'),
        ),
    ]
