import os


API_TOKEN = os.environ.get('API_TOKEN')
EVENT_CONTENT_ID = os.environ.get('EVENT_CONTENT_ID')
EVENT_TEMPLATE_ID = os.getenv('EVENT_TEMPLATE_ID')
WELCOME_EMAIL_CONTENT_ID = os.getenv('WELCOME_EMAIL_CONTENT_ID')
WELCOME_EMAIL_TEMPLATE_ID = os.getenv('WELCOME_EMAIL_TEMPLATE_ID')
CONFIRM_EMAIL_URL = os.getenv('CONFIRM_EMAIL_URL')
NEW_MOVIES_URL = os.getenv('NEW_MOVIES_URL')
NEW_MOVIES_TEMPLATE_ID = os.getenv('NEW_MOVIES_TEMPLATE_ID')
UNSUBSCRIBE_URL = os.getenv('UNSUBSCRIBE_URL')
