name: Notification check

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.9', '3.10']

    steps:

    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - name: Set up Python
      id: setup_python
      uses: actions/setup-python@v4
      if: ${{always()}}
      with:
        python-version: ${{ matrix.version }}

    - name: Install dependencies
      id: install_dependencies
      if: ${{always()}}
      run: |
        python -m pip install --upgrade pip
        pip install flake8-html mypy lxml wemake-python-styleguide

    - name: Make reports directory
      id: make_directories
      if: ${{always()}}
      run: |
        mkdir -p report/flake_report/
        mkdir -p report/mypy_report/

    - name: Lint with flake8
      id: flake8
      if: ${{always()}}
      run: flake8 srv_admin_panel srv_api srv_scheduler srv_worker --exit-zero --format=html --htmldir=report/flake_report/

    - name: Typo check with MyPy
      id: mypy
      if: ${{always()}}
      run: mypy . --pretty --ignore-missing-imports --html-report report/mypy_report/

    - name: Uploads reports
      id: upload_reports
      if: ${{always()}}
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: report/**/*

    - name: Send telegram message
      if: ${{success()}}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Repository: ${{ github.repository }}
          Branch: ${{ github.head_ref }}
          Pipeline for ${{ github.sha }} finished successfully

    - name: Send telegram message
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      if: ${{failure()}}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Repository: ${{ github.repository }}
          Branch: ${{ github.head_ref }}
          Pipeline for ${{ github.sha }} finished with error.
          Steps: ${{ toJson(steps) }}
