name: Notification check

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.9', '3.10']

    steps:
    - uses: actions/checkout@v3

    - name: Echo GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github.steps) }}
      run: echo $GITHUB_CONTEXT    
          
